export const ARIA2_ERROR_CODES: Record<string, string> = {
  "1": "Unknown error",
  "2": "Timeout",
  "3": "Resource not found",
  "4": "Too many file-not-found responses",
  "5": "Download too slow",
  "6": "Network error",
  "7": "Unfinished download",
  "8": "Resume failed",
  "9": "Disk full",
  "10": "Piece length mismatch",
  "11": "Duplicate file",
  "12": "Duplicate torrent",
  "13": "File exists",
  "14": "Rename failed",
  "15": "File open failed",
  "16": "File create failed",
  "17": "I/O error",
  "18": "Directory create failed",
  "19": "DNS failure",
  "20": "Metalink parse failed",
  "21": "FTP error",
  "22": "HTTP response error",
  "23": "Too many redirects",
  "24": "HTTP authentication failed",
  "25": "Bencode parse failed",
  "26": "Torrent corrupt",
  "27": "Bad magnet URI",
  "28": "Bad option",
  "29": "Server unavailable",
  "30": "JSON-RPC parse failed",
  "32": "Checksum mismatch",
}
